# Generated by Django 4.1.7 on 2023-02-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('PD', 'Pending'), ('CP', 'Completed'), ('IP', 'In Progress'), ('DP', 'Dropped')], default='Pending', max_length=2),
        ),
    ]
