# Generated by Django 4.1.7 on 2023-03-01 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='project',
        ),
        migrations.AddField(
            model_name='choice',
            name='option1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='option2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='option3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='option4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choice', to='webapp.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('Multiple Choice Checkbox', 'Multiple Choice Checkbox'), ('Field', 'Field'), ('Multiple Choice', 'Multiple Choice')], default='TEXT', max_length=255),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='webapp.project')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='webapp.question')),
                ('questionaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionaire', to='webapp.questionaire')),
            ],
        ),
    ]
