# Generated by Django 4.1.7 on 2023-03-01 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_choice_option1_alter_choice_option2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionaire',
            old_name='option1',
            new_name='name',
        ),
    ]
