# Generated by Django 4.1.7 on 2023-03-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_rename_option1_questionaire_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='questionaire',
        ),
        migrations.DeleteModel(
            name='Questionaire',
        ),
    ]
