# Generated by Django 4.1.7 on 2023-03-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_answer_questionaire_delete_questionaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='user',
        ),
    ]
