# Generated by Django 4.1.7 on 2023-03-04 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_questionaire_remove_question_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='project',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='webapp.project'),
            preserve_default=False,
        ),
    ]
