# Generated by Django 4.1.7 on 2023-03-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_choice_question_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.project'),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='webapp.question'),
        ),
    ]
