# Generated by Django 4.1.7 on 2023-03-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_questionaire_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionaire',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='webapp.choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='webapp.question'),
        ),
    ]
