# Generated by Django 4.1.7 on 2023-03-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_question_questionaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_questionaire', to='webapp.questionaire'),
        ),
    ]
