# Generated by Django 4.1.7 on 2023-03-06 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_remove_question_questionaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='questionaire',
        ),
        migrations.RemoveField(
            model_name='questionaire',
            name='project',
        ),
        migrations.AddField(
            model_name='answer',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='webapp.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='questionaire',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='questionaire', to='webapp.questionaire'),
            preserve_default=False,
        ),
    ]
