# Generated by Django 4.1.7 on 2023-03-06 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_remove_answer_questionaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='webapp.project'),
        ),
    ]
