# Generated by Django 4.1.7 on 2023-03-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_alter_question_questionaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
