# Generated by Django 4.1.7 on 2023-03-06 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_alter_question_questionaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionaire',
        ),
        migrations.AlterField(
            model_name='answer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='webapp.project'),
        ),
        migrations.DeleteModel(
            name='Questionaire',
        ),
    ]
