# Generated by Django 4.1.7 on 2023-03-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_remove_question_questionaire_alter_answer_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='project',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='webapp.project')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='response', to='webapp.response'),
            preserve_default=False,
        ),
    ]
