# Generated by Django 4.1.7 on 2023-03-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_alter_answer_choice_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.ManyToManyField(to='webapp.choice'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('PD', 'Pending'), ('CP', 'Completed'), ('IP', 'In Progress'), ('DP', 'Dropped')], default='PD', max_length=2),
        ),
    ]
