# Generated by Django 4.1.7 on 2023-03-09 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_remove_answer_answer_text_remove_answer_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='questionaire', to='webapp.response'),
            preserve_default=False,
        ),
    ]
