# Generated by Django 4.1.7 on 2023-03-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0035_question_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.response'),
        ),
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.response'),
        ),
    ]
