# Generated by Django 4.1.7 on 2023-03-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_alter_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='response',
        ),
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='webapp.response'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.question'),
        ),
    ]
