# Generated by Django 4.1.7 on 2023-03-09 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_remove_question_response_alter_answer_response_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Survey',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='response',
        ),
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='webapp.survey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionaire', to='webapp.survey'),
        ),
    ]
