# Generated by Django 4.1.7 on 2023-03-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_rename_response_survey_remove_answer_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ManyToManyField(to='webapp.survey'),
        ),
    ]
