# Generated by Django 4.1.7 on 2023-03-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_remove_question_survey_question_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
