# Generated by Django 4.1.7 on 2023-03-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_answer_question_alter_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ManyToManyField(blank=True, to='webapp.survey'),
        ),
    ]
