# Generated by Django 4.1.7 on 2023-03-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0046_alter_question_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answer_choice',
        ),
    ]
