# Generated by Django 4.1.7 on 2023-03-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0047_rename_answer_answer_answer_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
    ]
